id: P004377
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS19015
  title: ཞལ་གདམས་བསྡུས་འགྲེལ་སྐོར།
  author: ''
  volumes:
    11cbf9aa081044638f73a80429bdffc4:
      image_group_id: I8LS19017
      title: ''
      volume_number: 1
      total_pages: 436
