id: I81C928B8
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T11:28:55+00:00'
last_modified: '2022-06-07T22:25:27.065470+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS19015
  title: ཞལ་གདམས་བསྡུས་འགྲེལ་སྐོར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    D3F4:
      image_group_id: I8LS19017
      title: ''
      total_pages: 436
      order: 1
      base_file: D3F4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
